site_name: APEG
theme: material
repo_url: https://github.com/BOLDLab/learning_tools_integration
site_author: Paul Sijpkes
google_analytics: ["UA-80175715-1", "bold.newcastle.edu.au/padocs"]
copyright: "<a href='https://bold.newcastle.edu.au'>The BOLD Team, The University of Newcastle, Australia</a></sub><br><sub><em>A living document</em> [rev. 1.4]</sub>"
extra:
    version: 0.8.29
