site_name: APEG
theme: flatly
repo_url: https://github.com/BOLDLab/lti_peer_assessment
site_author: Paul Sijpkes
google_analytics: ["UA-80175715-1", "bold.newcastle.edu.au/padocs"]
copyright: "<a href='mailto:paul.sijpkes@newcastle.edu.au;paul.sijpkes@gmail.com'>Developer: Paul Sijpkes</a><br> <a href='https://bold.newcastle.edu.au'>The BOLD Team, The University of Newcastle, Australia</a></sub><br><sub><em>A living document</em> [rev. 1.3]</sub>
"
extra:
    version: 0.8.29
